//Auth
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const AUTH_USER = 'AUTH_USER';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const AUTH_CHECK = 'AUTH_CHECK';

//Connection
export const CONNECTION_ESTABLISHED = 'CONNECTION_ESTABLISHED';
export const CONNECTION_ENDED = 'CONNECTION_ENDED';
export const RECEIVED_MESSAGE = 'RECEIVED_MESSAGE';
export const SENT_MESSAGE = 'SENT_MESSAGE';
export const ENABLE_VIDEO = 'ENABLE_VIDEO';
export const DISABLE_VIDEO = 'DISABLE_VIDEO';
export const TOGGLE_VIDEO = 'TOGGLE_VIDEO';
export const ENABLE_AUDIO = 'ENABLE_AUDIO';
export const DISABLE_AUDIO = 'DISABLE_AUDIO';
export const ENABLE_SOUND = 'ENABLE_SOUND';
export const DISABLE_SOUND = 'DISABLE_SOUND';
export const SET_SUGGESTION = 'SET_SUGGESTION';
export const CLICKED_SUGGESTION = 'CLICKED_SUGGESTION';
export const ACCEPT_COMMUNICATION = 'ACCEPT_COMMUNICATION';
export const DENY_COMMUNICATION = 'DENY_COMMUNICATION';
export const OTHER_VIDEO = 'OTHER_VIDEO';

//User
export const CHANGE_SETTINGS = 'CHANGE_SETTINGS';
