//Auth
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_ERROR = 'LOGOUT_ERROR';
export const AUTH_USER = 'AUTH_USER';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const AUTH_CHECK = 'AUTH_CHECK';

//Connection
export const CONNECTION_ESTABLISHED = 'CONNECTION_ESTABLISHED';
export const CONNECTION_ENDED = 'CONNECTION_ENDED';
export const RECEIVED_MESSAGE = 'RECEIVED_MESSAGE';
export const SENT_MESSAGE = 'SENT_MESSAGE';
export const DISABLE_VIDEO = 'DISABLE_VIDEO';
export const TOGGLE_VIDEO = 'TOGGLE_VIDEO';
export const SET_SUGGESTION = 'SET_SUGGESTION';
export const CLICKED_SUGGESTION = 'CLICKED_SUGGESTION';
export const ACCEPT_COMMUNICATION = 'ACCEPT_COMMUNICATION';
export const DENY_COMMUNICATION = 'DENY_COMMUNICATION';
export const OTHER_VIDEO = 'OTHER_VIDEO';
export const FRIEND_DATA = 'FRIEND_DATA';
export const SET_SOCKET = 'SET_SOCKET';
export const SEARCH_STATE = 'SEARCH_STATE';
export const FRIEND_DISCONNECTED = 'FRIEND_DISCONNECTED';

//Scheduler
export const GET_SCHEDULE = 'GET_SCHEDULE';
export const PUT_SCHEDULE = 'PUT_SCHEDULE';
export const SCHEDULE_ERROR = 'SCHEDULE_ERROR';
